using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;
using UnityEngine.InputSystem;
using UnityEngine.EventSystems;

public class InputManager : MonoBehaviour, InputMap.IPlayerActions
{
    // Reference to the InputMap class, which is generated by the Input system
    InputMap inputMap;

    // Start is called before the first frame update
    void Start()
    {
        // Initalizing the InputMap instance
        inputMap = new InputMap();

        // Enable the player action map to start listening for player input
        inputMap.Player.Enable();

        // Set this script (InputManager) as the callback handler for player actions
        // This ensures methods like OnMove are called when the respective inputs are performed
        inputMap.Player.SetCallbacks(this);
    }

    public void OnMove(InputAction.CallbackContext context)
    {

    }

    public void OnInteract(InputAction.CallbackContext context)
    {
        if(context.started)
        {
            Actions.InteractStartedEvent?.Invoke();
            //Debug.Log("Interact was pressed:" + context.phase);
        }

        if (context.performed)
        {
            //Debug.Log("Interact was pressed:" + context.phase);
        }

        if (context.canceled)
        {
            //Debug.Log("Interact was pressed:" + context.phase);
        }
    }

    void OnDisable()
    {
        inputMap.Player.Disable();
    }


}

public static class Actions
{
    public static Action InteractStartedEvent;
}
